### ISSUE TITLE
Boost always builds up

### ISSUE THREAD

**Issue by robertodr** [robertodr/boost_cmake#1]
Whenever `make` is issued in the build directory, Boost build up fires up, even when nothing was touched. @bast any ideas for a possible fix?

**Comment by robertodr** [comment]
Closed via PR #2

**Comment by bast** [comment]
I am not sure my commit fixed it - I thought this was an unrelated problem.

**Comment by robertodr** [comment]
It didn't in fact... I was too quick...

**Comment by bast** [comment]
If I fix this one, I will auto-close it with a commit message :-)

**Comment by robertodr** [comment]
@bast it is still rebuilding every time I hit make

**Comment by bast** [comment]
True. Strange. I will look at it.

P.S.: BTW not needed to re-mention my username. Once I have been mentioned I stay
informed (unless of course I decide to deliberately unwatch).

**Comment by robertodr** [comment]
True. Sorry, still not used to program collaboratively...

**Comment by bast** [comment]
On the right side you can see who is watching this (now 2 participants).

**Comment by robertodr** [comment]
BTW, I forgot to reopen so that we do not forget.

**Comment by bast** [comment]
I realize that I did it wrong. It is so curious that it "worked" for me. I am on it.
